version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  service_net:

# the order the services are declared is the order they needto start in
services:
  
  eureka-server:
    build:
      context: ./ps-eureka-server
    ports:
      - 8761:8761
    environment:
      SERVER_PORT: 8761
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - service_net

  config-server:
    build:
      context: ./ps-config-server
    ports:
      - 8888:8888
    environment:
      SERVER_PORT: 8888
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka"
      EUREKA_SERVER_PORT: "8761"
    networks:
      - service_net

  admin-server:
    build:
      context: ./ps-admin-server
    ports:
      - 9000:9000
    environment:
      SERVER_PORT: 9000
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka"
      EUREKA_SERVER_PORT: "8761"
      CONFIG_SERVER_URI: "http://config-server:8888"
      CONFIG_SERVER_PORT: "8888"
    networks:
      - service_net
        
  router:
    build:
      context: ./ps-router
    ports:
      - 8060:8060
    environment:
      SERVER_PORT: 8060
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka"
      EUREKA_SERVER_PORT: "8761"
      CONFIG_SERVER_URI: "http://config-server:8888"
      CONFIG_SERVER_PORT: "8888"
    networks:
      - service_net

  service-a:
    build:
      context: ./ps-service-a
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka"
      EUREKA_SERVER_PORT: "8761"
      CONFIG_SERVER_URI: "http://config-server:8888"
      CONFIG_SERVER_PORT: "8888"
    networks:
      - service_net

 
  service-b:
    build:
      context: ./ps-service-b
    ports:
      - 8081:8081
    environment:
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka"
      EUREKA_SERVER_PORT: "8761"
      CONFIG_SERVER_URI: "http://config-server:8888"
      CONFIG_SERVER_PORT: "8888"
    networks:
      - service_net

  client:
    build:
      context: ./ps-client
    ports:
      - 80:80
    networks:
      - service_net

  tester:
    build:
      context: ./ps-tester
    networks:
      - service_net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./ps-prometheus-main:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - service_net
