version: '3'

networks:
  service_net:

services:
  
  eureka_server:
    build:
      context: ./ps-eureka-server
    ports:
      - 8761:80
    environment:
      SERVER_PORT: 80
      SPRING_PROFILES_ACTIVE: cloud, docker
    networks:
      - service_net

  client:
    build:
      context: ./ps-client
    networks:
      - service_net

  tester:
    build:
      context: ./ps-tester
    networks:
      - service_net

  config_server:
    build:
      context: ./ps-config-server
    environment:
      SERVER_PORT: 80
      SPRING_PROFILES_ACTIVE: cloud, docker
    networks:
      - service_net

  admin_server:
    build:
      context: ./ps-admin-server
    ports:
      - 9000:80
    environment:
      SERVER_PORT: 80
      SPRING_PROFILES_ACTIVE: cloud, docker
    networks:
      - service_net

  router:
    build:
      context: ./ps-router
    environment:
      SERVER_PORT: 80
      SPRING_PROFILES_ACTIVE: cloud, docker
    networks:
      - service_net

  web_service:
    build:
      context: ./ps-sample-service
    environment:
      SERVER_PORT: 80
      SPRING_PROFILES_ACTIVE: cloud, docker
    networks:
      - service_net
